hibernate:
  dialect: org.hibernate.dialect.HSQLDialect
  show_sql: true
  hbm2ddl.auto: update

spring:
  datasource:
    url: jdbc:hsqldb:mem
    username:
    password:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    tomcat:
      max-wait: 10000
      max-active: 50
      max-idle: 50
      test-on-borrow: true
      test-on-return: true
  jpa:
    database: HSQL
    show-sql: true